title: kili kipisi
description: sitelen musi pi jan Pensamin
author: jan Pensamin
collections:
  lipu:
    output: true
    permalink: /:name:output_ext
feed:
  collections:
    lipu:
      path: /lipu-sin.xml
exclude:
  - feed.xml
  - readme.md
plugins:
- jekyll-feed
