title: kili kipisi
description: sitelen musi pi jan Pensamin
author: jan Pensamin
collections:
  lipu:
    output: true
    permalink: /:name
feed:

  collections:
    lipu:
      path: /lipu-sin.atom
exclude:
  - /feed.xml
  - readme.md
plugins:
- jekyll-feed
